"""add message_meta to messages

Revision ID: 9f85103606c1
Revises: 6e8f3d108220
Create Date: 2026-02-05 01:16:33.055603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f85103606c1'
down_revision: Union[str, Sequence[str], None] = '6e8f3d108220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_meta', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('messages_conversation_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_conversation_id_fkey'), 'messages', 'conversations', ['conversation_id'], ['id'])
    op.drop_column('messages', 'message_meta')
    # ### end Alembic commands ###
