from enum import Enum
from typing import Any, Dict, List
from pydantic import BaseModel, Field, validator


class PatchOperation(str, Enum):
    REPLACE_TEXT = "replace_text"
    UPDATE_TABLE_CELL = "update_table_cell"
    UPDATE_FORMULA = "update_formula"
    INSERT_BLOCK = "insert_block"
    DELETE_BLOCK = "delete_block"
    UPDATE_IMAGE_CAPTION = "update_image_caption"


class PatchInstruction(BaseModel):
    """
    Deterministic patch instruction.

    Generated by patch_planner.
    Executed by editors.
    """

    operation: PatchOperation

    # Explicit targets only
    target_block_ids: List[str] = Field(
        ..., description="Exact blocks to modify"
    )

    # Operation-specific payload
    payload: Dict[str, Any]

    # Safety guardrails
    reason: str = Field(
        ..., description="Why this patch is required"
    )

    @validator("target_block_ids")
    def targets_not_empty(cls, v):
        if not v:
            raise ValueError("Patch must target at least one block")
        return v